[package]
name = "example-addon-rust"
version = "0.1.0"
authors = ["Ivo Georgiev <ivo@strem.io>"]
edition = "2018"

[dependencies]
hyper = "0.12.9"
futures = "0.1"
tokio = { version = "0.1" }
lazy_static = "1.3"

[profile.release]
lto = true
